overrides:
  '@xmldom/xmldom': ^0.9.10
  esbuild: ^0.28.0
  postcss: ^8.5.14
  eslint: ^10.0.2
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.1.1

allowBuilds:
  '@ampproject/toolbox-optimizer': set this to true or false
  better-sqlite3: true
  core-js: true
  es5-ext: true
  esbuild: true
  fsevents: set this to true or false
  msw: true
  sharp: true
  unrs-resolver: true
