export type EpubTheme = "light" | "dark" | "sepia";

export const THEME_STYLES: Record<
  EpubTheme,
  Record<string, Record<string, string>>
> = {
  light: {
    html: { background: "#ffffff", "overflow-x": "hidden" },
    body: {
      background: "#ffffff",
      color: "#171717",
      "font-family": '"Lora", "Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", serif',
      "line-height": "1.85",
      "letter-spacing": "0.012em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "4rem",
      "padding-bottom": "6rem",
      "padding-left": "2rem",
      "padding-right": "2rem",
      margin: "0 auto",
      "max-width": "44em",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
      "overflow-x": "hidden",
    },
    "body > *": {
      width: "100%",
      "max-width": "100%",
      "margin-left": "auto",
      "margin-right": "auto",
      "box-sizing": "border-box",
    },
    p: { margin: "0 0 1.5em", "text-align": "justify", "text-justify": "inter-character" },
    "h1, h2, h3, h4, h5, h6": {
      color: "#171717",
      "font-weight": "700",
      "line-height": "1.25",
      "margin-top": "2.5em",
      "margin-bottom": "1.2em",
      "letter-spacing": "-0.02em",
      "text-align": "left",
      "text-wrap": "balance",
    },
    h1: { "font-size": "2.4em", "border-bottom": "2px solid #171717", "padding-bottom": "0.4em", "margin-top": "0.5em" },
    h2: { "font-size": "1.8em" },
    h3: { "font-size": "1.4em", "font-style": "italic" },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "4em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent, #171717, transparent)",
      opacity: "0.2",
    },
    blockquote: {
      margin: "2em 0",
      padding: "1.2em 2em",
      "border-left": "2px solid #171717",
      background: "#fafafa",
      "font-style": "italic",
      color: "#404040",
    },
    pre: {
      margin: "2em 0",
      padding: "1.5em",
      "border-radius": "8px",
      background: "#f5f5f5",
      border: "1px solid #e5e5e5",
      "font-family": '"JetBrains Mono", monospace',
      "font-size": "0.9em",
      "line-height": "1.6",
      overflow: "auto",
      "white-space": "pre-wrap",
    },
    code: {
      padding: "0.2em 0.4em",
      "border-radius": "4px",
      background: "#f5f5f5",
      "font-family": '"JetBrains Mono", monospace',
      "font-size": "0.85em",
    },
    "img, svg, video, canvas": {
      "max-width": "100%",
      "max-height": "100vh",
      height: "auto",
      width: "auto",
      "border-radius": "4px",
      "box-shadow": "0 10px 30px rgba(0,0,0,0.08)",
      margin: "2em auto",
      display: "block",
      "object-fit": "contain",
    },
    table: {
      margin: "2.5em 0",
      width: "100%",
      "border-collapse": "collapse",
      "font-size": "0.9em",
      "line-height": "1.5",
    },
    "th, td": {
      padding: "0.85rem 1rem",
      "text-align": "left",
      "border-bottom": "1px solid #e5e5e5",
    },
    th: {
      "font-weight": "700",
      color: "#171717",
      background: "#fafafa",
      "border-bottom": "2px solid #171717",
    },
    "tr:last-child td": {
      "border-bottom": "none",
    },
  },
  dark: {
    html: { background: "#0a0a0a" },
    body: {
      background: "#0a0a0a",
      color: "#ededed",
      "font-family": '"Lora", "Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", serif',
      "line-height": "1.85",
      "letter-spacing": "0.012em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "4rem",
      "padding-bottom": "6rem",
      "padding-left": "2rem",
      "padding-right": "2rem",
      margin: "0 auto",
      "max-width": "44em",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
      "overflow-x": "hidden",
    },
    "body > *": { width: "100%", "max-width": "100%", "margin-left": "auto", "margin-right": "auto", "box-sizing": "border-box" },
    p: { margin: "0 0 1.5em", "text-align": "justify", "text-justify": "inter-character" },
    "h1, h2, h3, h4, h5, h6": {
      color: "#ffffff",
      "font-weight": "700",
      "line-height": "1.25",
      "margin-top": "2.5em",
      "margin-bottom": "1.2em",
      "letter-spacing": "-0.02em",
      "text-align": "left",
      "text-wrap": "balance",
    },
    h1: { "font-size": "2.4em", "border-bottom": "2px solid #ffffff", "padding-bottom": "0.4em", "margin-top": "0.5em" },
    h2: { "font-size": "1.8em" },
    h3: { "font-size": "1.4em", "font-style": "italic" },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "4em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent, #ffffff, transparent)",
      opacity: "0.2",
    },
    blockquote: {
      margin: "2em 0",
      padding: "1.2em 2em",
      "border-left": "2px solid #ffffff",
      background: "#171717",
      "font-style": "italic",
      color: "#d4d4d4",
    },
    pre: {
      margin: "2em 0",
      padding: "1.5em",
      "border-radius": "8px",
      background: "#171717",
      border: "1px solid #262626",
      "font-family": '"JetBrains Mono", monospace',
      "font-size": "0.9em",
      "line-height": "1.6",
      overflow: "auto",
      "white-space": "pre-wrap",
    },
    code: {
      padding: "0.2em 0.4em",
      "border-radius": "4px",
      background: "#171717",
      "font-family": '"JetBrains Mono", monospace',
      "font-size": "0.85em",
    },
    "img, svg, video, canvas": { "max-width": "100%", "max-height": "100vh", height: "auto", width: "auto", "border-radius": "4px", "box-shadow": "0 10px 40px rgba(0,0,0,0.4)", margin: "2em auto", display: "block", "object-fit": "contain" },
    table: {
      margin: "2.5em 0",
      width: "100%",
      "border-collapse": "collapse",
      "font-size": "0.9em",
      "line-height": "1.5",
    },
    "th, td": {
      padding: "0.85rem 1rem",
      "text-align": "left",
      "border-bottom": "1px solid #262626",
    },
    th: {
      "font-weight": "700",
      color: "#ffffff",
      background: "#171717",
      "border-bottom": "2px solid #ffffff",
    },
    "tr:last-child td": {
      "border-bottom": "none",
    },
  },
  sepia: {
    html: { background: "#F5F1E8", "overflow-x": "hidden" },
    body: {
      background: "#F5F1E8",
      color: "#5B4636",
      "font-family": '"Lora", "Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", serif',
      "line-height": "1.85",
      "letter-spacing": "0.012em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "4rem",
      "padding-bottom": "6rem",
      "padding-left": "2rem",
      "padding-right": "2rem",
      margin: "0 auto",
      "max-width": "44em",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
      "overflow-x": "hidden",
    },
    "body > *": { width: "100%", "max-width": "100%", "margin-left": "auto", "margin-right": "auto", "box-sizing": "border-box" },
    p: { margin: "0 0 1.5em", "text-align": "justify", "text-justify": "inter-character" },
    "h1, h2, h3, h4, h5, h6": {
      color: "#4C382B",
      "font-weight": "700",
      "line-height": "1.25",
      "margin-top": "2.5em",
      "margin-bottom": "1.2em",
      "letter-spacing": "-0.02em",
      "text-align": "left",
      "text-wrap": "balance",
    },
    h1: { "font-size": "2.4em", "border-bottom": "2px solid #5B4636", "padding-bottom": "0.4em", "margin-top": "0.5em" },
    h2: { "font-size": "1.8em" },
    h3: { "font-size": "1.4em", "font-style": "italic" },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "4em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent, #5B4636, transparent)",
      opacity: "0.2",
    },
    blockquote: {
      margin: "2em 0",
      padding: "1.2em 2em",
      "border-left": "2px solid #5B4636",
      background: "rgba(91,70,54,0.05)",
      "font-style": "italic",
      color: "#5B4636",
    },
    pre: {
      margin: "2em 0",
      padding: "1.5em",
      "border-radius": "8px",
      background: "rgba(91,70,54,0.05)",
      border: "1px solid rgba(91,70,54,0.1)",
      "font-size": "0.9em",
      "line-height": "1.6",
      overflow: "auto",
      "white-space": "pre-wrap",
    },
    code: {
      padding: "0.2em 0.4em",
      "border-radius": "4px",
      background: "rgba(91,70,54,0.05)",
      "font-family": '"JetBrains Mono", monospace',
      "font-size": "0.85em",
    },
    "img, svg, video, canvas": { "max-width": "100%", "max-height": "100vh", height: "auto", width: "auto", "border-radius": "4px", "box-shadow": "0 10px 30px rgba(91,70,54,0.15)", margin: "2em auto", display: "block", "object-fit": "contain" },
    "a:hover": { "text-decoration": "underline", "text-decoration-color": "rgba(91,70,54,0.3)" },
    table: {
      margin: "2.5em 0",
      width: "100%",
      "border-collapse": "collapse",
      "font-size": "0.9em",
      "line-height": "1.5",
    },
    "th, td": {
      padding: "0.85rem 1rem",
      "text-align": "left",
      "border-bottom": "1px solid rgba(91,70,54,0.1)",
    },
    th: {
      "font-weight": "700",
      color: "#5B4636",
      background: "rgba(91,70,54,0.05)",
      "border-bottom": "2px solid #5B4636",
    },
    "tr:last-child td": {
      "border-bottom": "none",
    },
  },
};