export type EpubTheme = "light" | "dark" | "sepia";

export const THEME_STYLES: Record<
  EpubTheme,
  Record<string, Record<string, string>>
> = {
  light: {
    html: { background: "#f5f7fb" },
    body: {
      background: "#f5f7fb",
      color: "hsl(240 10% 3.9%)",
      "font-family": '"Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", "ZCOOL XiaoWei", serif',
      "line-height": "1.78",
      "letter-spacing": "0.006em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "1.35rem",
      "padding-bottom": "2.5rem",
      "padding-left": "1rem",
      "padding-right": "1rem",
      margin: "0",
      width: "100%",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
    },
    "body > *": {
      width: "100%",
      "max-width": "100%",
      "margin-left": "auto",
      "margin-right": "auto",
      "box-sizing": "border-box",
    },
    p: { margin: "0 0 0.95em", "text-align": "justify", "text-indent": "2em" },
    "h1, h2, h3, h4, h5, h6": {
      color: "hsl(240 10% 3.9%)",
      "font-weight": "600",
      "line-height": "1.32",
      "margin-top": "1.75em",
      "margin-bottom": "0.85em",
      "letter-spacing": "0.018em",
      "text-align": "center",
      "text-wrap": "balance",
    },
    h1: { "font-size": "1.58em", "line-height": "1.22", "margin-top": "0.2em", "margin-bottom": "0.95em", "font-weight": "700" },
    h2: { "font-size": "1.24em", "margin-top": "2em", "margin-bottom": "0.9em" },
    h3: { "font-size": "1.12em", "margin-top": "1.7em", "margin-bottom": "0.75em" },
    "ul, ol": { margin: "0.95em 0 1.1em", padding: "0 0 0 1.65em" },
    li: { margin: "0.32em 0", "padding-left": "0.2em", "line-height": "1.72" },
    blockquote: {
      margin: "1.2em auto",
      padding: "0.9em 1.1em",
      "border-left": "4px solid rgba(24,24,27,0.18)",
      "border-radius": "1rem",
      background: "rgba(24,24,27,0.035)",
      color: "rgba(24,24,27,0.82)",
      "font-style": "italic",
    },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "2em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent 0%, rgba(24,24,27,0.2) 18%, rgba(24,24,27,0.2) 82%, transparent 100%)",
    },
    "pre, code, kbd": {
      "font-family": '"SFMono-Regular", "JetBrains Mono", "Fira Code", "Noto Sans Mono SC", "Courier New", monospace',
    },
    pre: {
      margin: "1.15em 0",
      padding: "0.9em 1em",
      "border-radius": "1rem",
      background: "rgba(24,24,27,0.05)",
      border: "1px solid rgba(24,24,27,0.1)",
      "font-size": "0.93em",
      "line-height": "1.58",
      overflow: "auto",
      "white-space": "pre-wrap",
    },
    code: { "font-size": "0.93em", background: "rgba(24,24,27,0.07)", "border-radius": "0.5rem", padding: "0.15em 0.4em" },
    "figure, .figure": { margin: "1.45em auto", "text-align": "center" },
    figcaption: { margin: "0.65em auto 0", "font-size": "0.89em", color: "rgba(24,24,27,0.58)", "line-height": "1.55" },
    "strong, b": { "font-weight": "700", color: "rgba(24,24,27,0.94)" },
    "em, i": { "font-style": "italic", color: "rgba(24,24,27,0.85)" },
    "img, svg, video, canvas": {
      "max-width": "100%",
      height: "auto",
      "border-radius": "1rem",
      "box-shadow": "0 18px 36px -28px rgba(15,23,42,0.38)",
    },
    sup: { "line-height": "1" },
    "a, a:visited": { color: "inherit", "text-decoration": "none" },
    "a:hover": { "text-decoration": "underline", "text-decoration-color": "rgba(24,24,27,0.3)" },
    table: { margin: "1.2em auto", "border-collapse": "collapse", width: "100%", "font-size": "0.95em" },
    th: { padding: "0.72em 1em", "border-bottom": "2px solid rgba(24,24,27,0.12)", "font-weight": "600", "text-align": "left" },
    td: { padding: "0.68em 1em", "border-bottom": "1px solid rgba(24,24,27,0.08)" },
  },
  dark: {
    html: { background: "#09090b" },
    body: {
      background: "#09090b",
      color: "hsl(0 0% 98%)",
      "font-family": '"Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", "ZCOOL XiaoWei", serif',
      "line-height": "1.78",
      "letter-spacing": "0.006em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "1.35rem",
      "padding-bottom": "2.5rem",
      "padding-left": "1rem",
      "padding-right": "1rem",
      margin: "0",
      width: "100%",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
    },
    "body > *": { width: "100%", "max-width": "100%", "margin-left": "auto", "margin-right": "auto", "box-sizing": "border-box" },
    p: { margin: "0 0 0.95em", "text-align": "justify", "text-indent": "2em" },
    "h1, h2, h3, h4, h5, h6": {
      color: "hsl(0 0% 98%)",
      "font-weight": "600",
      "line-height": "1.32",
      "margin-top": "1.75em",
      "margin-bottom": "0.85em",
      "letter-spacing": "0.018em",
      "text-align": "center",
      "text-wrap": "balance",
    },
    h1: { "font-size": "1.58em", "line-height": "1.22", "margin-top": "0.2em", "margin-bottom": "0.95em", "font-weight": "700" },
    h2: { "font-size": "1.24em", "margin-top": "2em", "margin-bottom": "0.9em" },
    h3: { "font-size": "1.12em", "margin-top": "1.7em", "margin-bottom": "0.75em" },
    "ul, ol": { margin: "0.95em 0 1.1em", padding: "0 0 0 1.65em" },
    li: { margin: "0.32em 0", "padding-left": "0.2em", "line-height": "1.72" },
    blockquote: {
      margin: "1.2em auto",
      padding: "0.9em 1.1em",
      "border-left": "4px solid rgba(255,255,255,0.22)",
      "border-radius": "1rem",
      background: "rgba(255,255,255,0.05)",
      color: "rgba(250,250,250,0.82)",
      "font-style": "italic",
    },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "2em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.24) 18%, rgba(255,255,255,0.24) 82%, transparent 100%)",
    },
    "pre, code, kbd": { "font-family": '"SFMono-Regular", "JetBrains Mono", "Fira Code", "Noto Sans Mono SC", "Courier New", monospace' },
    pre: { margin: "1.15em 0", padding: "0.9em 1em", "border-radius": "1rem", background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", "font-size": "0.93em", "line-height": "1.58", overflow: "auto", "white-space": "pre-wrap" },
    code: { "font-size": "0.93em", background: "rgba(255,255,255,0.09)", "border-radius": "0.5rem", padding: "0.15em 0.4em" },
    "figure, .figure": { margin: "1.45em auto", "text-align": "center" },
    figcaption: { margin: "0.65em auto 0", "font-size": "0.89em", color: "rgba(250,250,250,0.58)", "line-height": "1.55" },
    "strong, b": { "font-weight": "700", color: "rgba(250,250,250,0.96)" },
    "em, i": { "font-style": "italic", color: "rgba(250,250,250,0.85)" },
    "img, svg, video, canvas": { "max-width": "100%", height: "auto", "border-radius": "1rem", "box-shadow": "0 22px 40px -32px rgba(0,0,0,0.65)" },
    sup: { "line-height": "1" },
    "a, a:visited": { color: "inherit", "text-decoration": "none" },
    "a:hover": { "text-decoration": "underline", "text-decoration-color": "rgba(255,255,255,0.3)" },
    table: { margin: "1.2em auto", "border-collapse": "collapse", width: "100%", "font-size": "0.95em" },
    th: { padding: "0.72em 1em", "border-bottom": "2px solid rgba(255,255,255,0.15)", "font-weight": "600", "text-align": "left" },
    td: { padding: "0.68em 1em", "border-bottom": "1px solid rgba(255,255,255,0.1)" },
  },
  sepia: {
    html: { background: "#F5F1E8" },
    body: {
      background: "#F5F1E8",
      color: "#5B4636",
      "font-family": '"Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", "ZCOOL XiaoWei", serif',
      "line-height": "1.8",
      "letter-spacing": "0.007em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "1.45rem",
      "padding-bottom": "2.6rem",
      "padding-left": "1rem",
      "padding-right": "1rem",
      margin: "0",
      width: "100%",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
    },
    "body > *": { width: "100%", "max-width": "100%", "margin-left": "auto", "margin-right": "auto", "box-sizing": "border-box" },
    p: { margin: "0 0 1em", "text-align": "justify", "text-indent": "2em" },
    "h1, h2, h3, h4, h5, h6": {
      color: "#4C382B",
      "font-weight": "600",
      "line-height": "1.34",
      "margin-top": "1.8em",
      "margin-bottom": "0.88em",
      "letter-spacing": "0.018em",
      "text-align": "center",
      "text-wrap": "balance",
    },
    h1: { "font-size": "1.6em", "line-height": "1.24", "margin-top": "0.22em", "margin-bottom": "0.98em", "font-weight": "700" },
    h2: { "font-size": "1.26em", "margin-top": "2.05em", "margin-bottom": "0.92em" },
    h3: { "font-size": "1.13em", "margin-top": "1.75em", "margin-bottom": "0.78em" },
    "ul, ol": { margin: "1em 0 1.15em", padding: "0 0 0 1.65em" },
    li: { margin: "0.34em 0", "padding-left": "0.2em", "line-height": "1.74" },
    blockquote: {
      margin: "1.25em auto",
      padding: "0.92em 1.12em",
      "border-left": "4px solid rgba(91,70,54,0.2)",
      "border-radius": "1rem",
      background: "rgba(91,70,54,0.05)",
      color: "rgba(91,70,54,0.85)",
      "font-style": "italic",
    },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "2.05em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent 0%, rgba(91,70,54,0.22) 18%, rgba(91,70,54,0.22) 82%, transparent 100%)",
    },
    "pre, code, kbd": { "font-family": '"SFMono-Regular", "JetBrains Mono", "Fira Code", "Noto Sans Mono SC", "Courier New", monospace' },
    pre: { margin: "1.2em 0", padding: "0.9em 1em", "border-radius": "1rem", background: "rgba(91,70,54,0.07)", border: "1px solid rgba(91,70,54,0.1)", "font-size": "0.93em", "line-height": "1.6", overflow: "auto", "white-space": "pre-wrap" },
    code: { "font-size": "0.93em", background: "rgba(91,70,54,0.08)", "border-radius": "0.5rem", padding: "0.15em 0.4em" },
    "figure, .figure": { margin: "1.5em auto", "text-align": "center" },
    figcaption: { margin: "0.65em auto 0", "font-size": "0.89em", color: "rgba(91,70,54,0.6)", "line-height": "1.58" },
    "strong, b": { "font-weight": "700", color: "rgba(76,56,43,0.97)" },
    "em, i": { "font-style": "italic", color: "rgba(91,70,54,0.85)" },
    "img, svg, video, canvas": { "max-width": "100%", height: "auto", "border-radius": "1rem", "box-shadow": "0 18px 36px -28px rgba(91,70,54,0.36)" },
    sup: { "line-height": "1" },
    "a, a:visited": { color: "inherit", "text-decoration": "none" },
    "a:hover": { "text-decoration": "underline", "text-decoration-color": "rgba(91,70,54,0.3)" },
    table: { margin: "1.25em auto", "border-collapse": "collapse", width: "100%", "font-size": "0.95em" },
    th: { padding: "0.72em 1em", "border-bottom": "2px solid rgba(91,70,54,0.15)", "font-weight": "600", "text-align": "left" },
    td: { padding: "0.68em 1em", "border-bottom": "1px solid rgba(91,70,54,0.1)" },
  },
};
