export type EpubTheme = "light" | "dark" | "sepia";

export const THEME_STYLES: Record<
  EpubTheme,
  Record<string, Record<string, string>>
> = {
  light: {
    html: { background: "transparent" },
    body: {
      background: "transparent",
      color: "hsl(240 10% 3.9%)",
      "font-family": '"Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", "ZCOOL XiaoWei", serif',
      "line-height": "2.12",
      "letter-spacing": "0.015em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "2.8rem",
      "padding-bottom": "5.2rem",
      "padding-left": "1.35rem",
      "padding-right": "1.35rem",
      margin: "0",
      width: "100%",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
    },
    "body > *": {
      width: "100%",
      "max-width": "100%",
      "margin-left": "auto",
      "margin-right": "auto",
      "box-sizing": "border-box",
    },
    p: { margin: "0 0 1.65em", "text-align": "justify", "text-indent": "2em" },
    "h1, h2, h3, h4, h5, h6": {
      color: "hsl(240 10% 3.9%)",
      "font-weight": "600",
      "line-height": "1.45",
      "margin-top": "2.65em",
      "margin-bottom": "1.15em",
      "letter-spacing": "0.032em",
      "text-align": "center",
      "text-wrap": "balance",
    },
    h1: { "font-size": "1.78em", "line-height": "1.32", "margin-top": "0.5em", "margin-bottom": "1.35em", "font-weight": "700" },
    h2: { "font-size": "1.32em", "margin-top": "3em", "margin-bottom": "1.2em" },
    h3: { "font-size": "1.15em", "margin-top": "2.5em", "margin-bottom": "1em" },
    "ul, ol": { margin: "1.45em 0 1.7em", padding: "0 0 0 1.8em" },
    li: { margin: "0.52em 0", "padding-left": "0.25em", "line-height": "2.02" },
    blockquote: {
      margin: "1.85em auto",
      padding: "1.12em 1.35em",
      "border-left": "4px solid rgba(24,24,27,0.18)",
      "border-radius": "1rem",
      background: "rgba(24,24,27,0.035)",
      color: "rgba(24,24,27,0.82)",
      "font-style": "italic",
    },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "3em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent 0%, rgba(24,24,27,0.2) 18%, rgba(24,24,27,0.2) 82%, transparent 100%)",
    },
    "pre, code, kbd": {
      "font-family": '"SFMono-Regular", "JetBrains Mono", "Fira Code", "Noto Sans Mono SC", "Courier New", monospace',
    },
    pre: {
      margin: "1.75em 0",
      padding: "1.05em 1.2em",
      "border-radius": "1rem",
      background: "rgba(24,24,27,0.05)",
      border: "1px solid rgba(24,24,27,0.1)",
      "font-size": "0.93em",
      "line-height": "1.78",
      overflow: "auto",
      "white-space": "pre-wrap",
    },
    code: { "font-size": "0.93em", background: "rgba(24,24,27,0.07)", "border-radius": "0.5rem", padding: "0.15em 0.4em" },
    "figure, .figure": { margin: "2.2em auto", "text-align": "center" },
    figcaption: { margin: "0.95em auto 0", "font-size": "0.89em", color: "rgba(24,24,27,0.58)", "line-height": "1.72" },
    "strong, b": { "font-weight": "700", color: "rgba(24,24,27,0.94)" },
    "em, i": { "font-style": "italic", color: "rgba(24,24,27,0.85)" },
    "img, svg, video, canvas": {
      "max-width": "100%",
      height: "auto",
      "border-radius": "1rem",
      "box-shadow": "0 18px 36px -28px rgba(15,23,42,0.38)",
    },
    sup: { "line-height": "1" },
    "a, a:visited": { color: "inherit", "text-decoration": "none" },
    "a:hover": { "text-decoration": "underline", "text-decoration-color": "rgba(24,24,27,0.3)" },
    table: { margin: "1.8em auto", "border-collapse": "collapse", width: "100%", "font-size": "0.95em" },
    th: { padding: "0.72em 1em", "border-bottom": "2px solid rgba(24,24,27,0.12)", "font-weight": "600", "text-align": "left" },
    td: { padding: "0.68em 1em", "border-bottom": "1px solid rgba(24,24,27,0.08)" },
  },
  dark: {
    html: { background: "transparent" },
    body: {
      background: "transparent",
      color: "hsl(0 0% 98%)",
      "font-family": '"Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", "ZCOOL XiaoWei", serif',
      "line-height": "2.12",
      "letter-spacing": "0.015em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "2.8rem",
      "padding-bottom": "5.2rem",
      "padding-left": "1.35rem",
      "padding-right": "1.35rem",
      margin: "0",
      width: "100%",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
    },
    "body > *": { width: "100%", "max-width": "100%", "margin-left": "auto", "margin-right": "auto", "box-sizing": "border-box" },
    p: { margin: "0 0 1.65em", "text-align": "justify", "text-indent": "2em" },
    "h1, h2, h3, h4, h5, h6": {
      color: "hsl(0 0% 98%)",
      "font-weight": "600",
      "line-height": "1.45",
      "margin-top": "2.65em",
      "margin-bottom": "1.15em",
      "letter-spacing": "0.032em",
      "text-align": "center",
      "text-wrap": "balance",
    },
    h1: { "font-size": "1.78em", "line-height": "1.32", "margin-top": "0.5em", "margin-bottom": "1.35em", "font-weight": "700" },
    h2: { "font-size": "1.32em", "margin-top": "3em", "margin-bottom": "1.2em" },
    h3: { "font-size": "1.15em", "margin-top": "2.5em", "margin-bottom": "1em" },
    "ul, ol": { margin: "1.45em 0 1.7em", padding: "0 0 0 1.8em" },
    li: { margin: "0.52em 0", "padding-left": "0.25em", "line-height": "2.02" },
    blockquote: {
      margin: "1.85em auto",
      padding: "1.12em 1.35em",
      "border-left": "4px solid rgba(255,255,255,0.22)",
      "border-radius": "1rem",
      background: "rgba(255,255,255,0.05)",
      color: "rgba(250,250,250,0.82)",
      "font-style": "italic",
    },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "3em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.24) 18%, rgba(255,255,255,0.24) 82%, transparent 100%)",
    },
    "pre, code, kbd": { "font-family": '"SFMono-Regular", "JetBrains Mono", "Fira Code", "Noto Sans Mono SC", "Courier New", monospace' },
    pre: { margin: "1.75em 0", padding: "1.05em 1.2em", "border-radius": "1rem", background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", "font-size": "0.93em", "line-height": "1.78", overflow: "auto", "white-space": "pre-wrap" },
    code: { "font-size": "0.93em", background: "rgba(255,255,255,0.09)", "border-radius": "0.5rem", padding: "0.15em 0.4em" },
    "figure, .figure": { margin: "2.2em auto", "text-align": "center" },
    figcaption: { margin: "0.95em auto 0", "font-size": "0.89em", color: "rgba(250,250,250,0.58)", "line-height": "1.72" },
    "strong, b": { "font-weight": "700", color: "rgba(250,250,250,0.96)" },
    "em, i": { "font-style": "italic", color: "rgba(250,250,250,0.85)" },
    "img, svg, video, canvas": { "max-width": "100%", height: "auto", "border-radius": "1rem", "box-shadow": "0 22px 40px -32px rgba(0,0,0,0.65)" },
    sup: { "line-height": "1" },
    "a, a:visited": { color: "inherit", "text-decoration": "none" },
    "a:hover": { "text-decoration": "underline", "text-decoration-color": "rgba(255,255,255,0.3)" },
    table: { margin: "1.8em auto", "border-collapse": "collapse", width: "100%", "font-size": "0.95em" },
    th: { padding: "0.72em 1em", "border-bottom": "2px solid rgba(255,255,255,0.15)", "font-weight": "600", "text-align": "left" },
    td: { padding: "0.68em 1em", "border-bottom": "1px solid rgba(255,255,255,0.1)" },
  },
  sepia: {
    html: { background: "transparent" },
    body: {
      background: "transparent",
      color: "#5B4636",
      "font-family": '"Baskerville", "Iowan Old Style", "Palatino Linotype", "Noto Serif SC", "Songti SC", "Source Han Serif SC", "LXGW WenKai", "ZCOOL XiaoWei", serif',
      "line-height": "2.18",
      "letter-spacing": "0.016em",
      "text-rendering": "optimizeLegibility",
      "-webkit-font-smoothing": "antialiased",
      "font-kerning": "normal",
      "word-break": "break-word",
      "overflow-wrap": "break-word",
      "padding-top": "2.95rem",
      "padding-bottom": "5.35rem",
      "padding-left": "1.35rem",
      "padding-right": "1.35rem",
      margin: "0",
      width: "100%",
      display: "flex",
      "flex-direction": "column",
      "align-items": "center",
      "box-sizing": "border-box",
    },
    "body > *": { width: "100%", "max-width": "100%", "margin-left": "auto", "margin-right": "auto", "box-sizing": "border-box" },
    p: { margin: "0 0 1.72em", "text-align": "justify", "text-indent": "2em" },
    "h1, h2, h3, h4, h5, h6": {
      color: "#4C382B",
      "font-weight": "600",
      "line-height": "1.48",
      "margin-top": "2.7em",
      "margin-bottom": "1.18em",
      "letter-spacing": "0.033em",
      "text-align": "center",
      "text-wrap": "balance",
    },
    h1: { "font-size": "1.82em", "line-height": "1.38", "margin-top": "0.52em", "margin-bottom": "1.38em", "font-weight": "700" },
    h2: { "font-size": "1.35em", "margin-top": "3.05em", "margin-bottom": "1.25em" },
    h3: { "font-size": "1.18em", "margin-top": "2.55em", "margin-bottom": "1.05em" },
    "ul, ol": { margin: "1.52em 0 1.78em", padding: "0 0 0 1.8em" },
    li: { margin: "0.55em 0", "padding-left": "0.25em", "line-height": "2.05" },
    blockquote: {
      margin: "1.92em auto",
      padding: "1.15em 1.38em",
      "border-left": "4px solid rgba(91,70,54,0.2)",
      "border-radius": "1rem",
      background: "rgba(91,70,54,0.05)",
      color: "rgba(91,70,54,0.85)",
      "font-style": "italic",
    },
    hr: {
      width: "6rem",
      height: "1px",
      margin: "3.05em auto",
      border: "0",
      background: "linear-gradient(90deg, transparent 0%, rgba(91,70,54,0.22) 18%, rgba(91,70,54,0.22) 82%, transparent 100%)",
    },
    "pre, code, kbd": { "font-family": '"SFMono-Regular", "JetBrains Mono", "Fira Code", "Noto Sans Mono SC", "Courier New", monospace' },
    pre: { margin: "1.8em 0", padding: "1.05em 1.2em", "border-radius": "1rem", background: "rgba(91,70,54,0.07)", border: "1px solid rgba(91,70,54,0.1)", "font-size": "0.93em", "line-height": "1.8", overflow: "auto", "white-space": "pre-wrap" },
    code: { "font-size": "0.93em", background: "rgba(91,70,54,0.08)", "border-radius": "0.5rem", padding: "0.15em 0.4em" },
    "figure, .figure": { margin: "2.25em auto", "text-align": "center" },
    figcaption: { margin: "0.95em auto 0", "font-size": "0.89em", color: "rgba(91,70,54,0.6)", "line-height": "1.75" },
    "strong, b": { "font-weight": "700", color: "rgba(76,56,43,0.97)" },
    "em, i": { "font-style": "italic", color: "rgba(91,70,54,0.85)" },
    "img, svg, video, canvas": { "max-width": "100%", height: "auto", "border-radius": "1rem", "box-shadow": "0 18px 36px -28px rgba(91,70,54,0.36)" },
    sup: { "line-height": "1" },
    "a, a:visited": { color: "inherit", "text-decoration": "none" },
    "a:hover": { "text-decoration": "underline", "text-decoration-color": "rgba(91,70,54,0.3)" },
    table: { margin: "1.85em auto", "border-collapse": "collapse", width: "100%", "font-size": "0.95em" },
    th: { padding: "0.72em 1em", "border-bottom": "2px solid rgba(91,70,54,0.15)", "font-weight": "600", "text-align": "left" },
    td: { padding: "0.68em 1em", "border-bottom": "1px solid rgba(91,70,54,0.1)" },
  },
};
